#!/usr/bin/env php
<?php
/**
 * Created by PhpStorm.
 * User: gsh
 * Date: 2019/6/3
 * Time: 5:14 PM
 */

use Myth\Generators\Make;

if (file_exists(__DIR__ . '/../../autoload.php')) {
    require __DIR__ . '/../../autoload.php';
} else {
    require __DIR__ . '/vendor/autoload.php';
}

$app = new Symfony\Component\Console\Application('Generator', '1.1.1');
$g = new Make();
$g->setLaravel(new \Illuminate\Container\Container());

$app->add($g);

$factoryGenerator = new \Myth\Generators\FactoryGenerator\FactoryGeneratorCommand();
$factoryGenerator->setLaravel(new \Illuminate\Container\Container());

$app->add($factoryGenerator);


$app->run();
